name: Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  BUILD_ENVIRONMENT: GitHub
  
jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        if: always()

      - name: Check file location
        run: |
          $csprojPath = "D:\a\${{github.event.repository.name}}\${{github.event.repository.name}}"
          cd $csprojPath
          dir
          cd ..
          dir
          cd ..
          dir

      - name: Extract Version from .csproj
        id: extract_version
        run: |
          # Replace 'YourProject.csproj' with the actual .csproj filename
          $csprojPath = ".\${{github.event.repository.name}}\${{github.event.repository.name}}.csproj"
          [xml]$csproj = Get-Content $csprojPath
          $version = $csproj.Project.PropertyGroup.Version
          echo "Version: $version"
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore "${{github.workspace}}/LibDemo.sln"

      - name: Build
        run: dotnet build "${{github.workspace}}/LibDemo.sln"  --no-restore --configuration Release

      - name: Publish
        run: dotnet publish "${{github.workspace}}/LibDemo/LibDemo.csproj" -c Release -o libdemo

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{github.event.repository.name}}"
          path: libdemo/**
          if-no-files-found: error

      - name: Download build artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          name: "${{github.event.repository.name}}"
          path: libdemo
          if-no-files-found: error

  pause-for-approval:
    needs: build
    runs-on: windows-2019

    steps:
        - name: Download jq
          run: |
            curl -L -o jq.exe https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
            mkdir -p C:\jq
            move jq.exe C:\jq\jq.exe
            $env:PATH = "C:\jq;" + $env:PATH
      
        - name: Verify jq Installation
          run: jq --version
    
        - name: Checking for Merge
          run: |
            $PULL_REQUEST_NUMBER = ${{ github.event.number }}
            $OWNER = "${{ github.event.organization.login }}"
            $REPO = "${{ github.event.repository.name }}"
            $TOKEN = "${{ secrets.GITHUB_TOKEN }}"
            while ($true) {
              $response = Invoke-RestMethod -Uri "https://api.github.com/repos/$OWNER/$REPO/pulls/$PULL_REQUEST_NUMBER" -Headers @{
                Authorization = "token $TOKEN"
                Accept = "application/vnd.github.v3+json"
              }
              $status = $response | Select-Object -ExpandProperty merged
              if ($status -eq $true) {
                Write-Host "Pull request is merged. Continuing workflow..."
                break
              } else {
                Write-Host "Pull request not yet merged. Waiting..."
                Start-Sleep -Seconds 60
              }
            }

  
  Publish:
      needs: pause-for-approval
      runs-on: windows-2019
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Restore cache for build
          uses: actions/cache@v3
          with:
            path: "${{github.workspace}}"
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/package-lock.json') }}
  
        - name: Download build artifacts
          uses: actions/download-artifact@v4.2.1
          with:
            name: "${{github.event.repository.name}}"
            path: libdemo/
            if-no-files-found: error          

        - name: Extract Version from .csproj
          id: extract_version
          run: |
            # Replace 'YourProject.csproj' with the actual .csproj filename
            $csprojPath = ".\${{github.event.repository.name}}\${{github.event.repository.name}}.csproj"
            [xml]$csproj = Get-Content $csprojPath
            $version = $csproj.Project.PropertyGroup.Version
            echo "Version: $version"
            echo "VERSION=$version" >> $env:GITHUB_ENV
              
        - name: Dump GitHub context2
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo "$GITHUB_CONTEXT"
          if: always()

        - name: List workspace contents
          run: ls -R
  
        - name: NuGet Login
          env: 
            NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/JTTesting/index.json"
        
        - name: Publish NuGet Package
          run: dotnet nuget push "${{github.workspace}}\LibDemo\bin\Release\LibDemo.$env:VERSION.nupkg" --source "github"
